# Managed services
version: '3.6'
services:
  rabbitmq:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/rabbitmq:3-management
    ports:
      - 15672
      - 5672
  mongodb:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/mongo:4.0.10
    ports:
      - 27017
  eureka:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/netflixoss/eureka:1.3.1
    ports:
      - 8080
      - 8761
  

# Tips:
# 1. Any services added to this file must leave the HOST portion of the port assignment blank to
# allow for random assignment on the Docker host.
# 2. Images must be hosted in Artifactory and should begin with: orion-team-docker-prod.mia.ulti.io/launch/path/to/image
