# Managed services
version: '3.6'
services:
  rabbitmq:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  mongodb:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/mongo:4.0.10
    ports:
      - 27017:27017
  eureka:
    image: orion-team-docker-dev.mia.ulti.io/launch/vendor/netflixoss/eureka:1.3.1
    ports:
      - 8080:8080
      - 8761:8761
  

  # Micro-service

#  project-query:
#    image: ulti/project-query
#    restart: always
#    ports:
#      - 8090:8080
